# =============================================================================
# Homelab Inventory System - Docker Build
# =============================================================================
# Multi-stage build for production deployment with Tailscale integration
# Supports both ARM64 (Raspberry Pi) and x86_64 (Intel/AMD) architectures
# =============================================================================

# -----------------------------------------------------------------------------
# Stage 1: Builder - Compile the Next.js application
# -----------------------------------------------------------------------------
FROM node:22-alpine AS builder

WORKDIR /app

# Install build dependencies for native modules (better-sqlite3, sharp)
RUN apk add --no-cache python3 make g++

# Copy package files first (better layer caching)
COPY package*.json ./

# Install all dependencies (including devDependencies for build)
RUN npm ci

# Copy source code
COPY . .

# Ensure public directory exists (Next.js standalone build needs it)
RUN mkdir -p public

# Build the Next.js application
# This creates .next/standalone with a minimal Node.js server
RUN npm run build

# Verify build outputs exist (fail fast if something went wrong)
RUN test -d .next/standalone || (echo "ERROR: standalone build not found" && exit 1)
RUN test -d .next/static || (echo "ERROR: static files not found" && exit 1)

# -----------------------------------------------------------------------------
# Stage 2: Runner - Production container with Tailscale
# -----------------------------------------------------------------------------
FROM node:22-alpine AS runner

WORKDIR /app

# Install runtime dependencies
# - tailscale: VPN/mesh networking for secure remote access
# - iptables/ip6tables: Required by Tailscale for networking
# - iproute2: Network utilities
# - supervisor: Process manager to run multiple services
# - wget: For health checks
# - ca-certificates: For HTTPS connections
RUN apk add --no-cache \
    tailscale \
    iptables \
    ip6tables \
    iproute2 \
    ca-certificates \
    supervisor \
    wget

# Create required directories
RUN mkdir -p \
    /var/run/tailscale \
    /var/lib/tailscale \
    /app/data \
    /app/public \
    /var/log/supervisor

# Copy standalone build from builder
# The standalone output includes only the necessary node_modules
COPY --from=builder /app/.next/standalone ./

# Copy static assets (CSS, JS, images generated by build)
COPY --from=builder /app/.next/static ./.next/static

# Copy public directory (favicon, robots.txt, etc.)
# Use --chown to ensure proper permissions
COPY --from=builder /app/public ./public

# Copy database schema and utilities for initialization
# These are needed to create the database on first run
COPY --from=builder /app/src/lib/db ./src/lib/db
COPY --from=builder /app/src/lib/utils ./src/lib/utils
COPY --from=builder /app/src/lib/types ./src/lib/types

# Copy and build MCP server
# This enables AI assistants to query the inventory
COPY --from=builder /app/mcp-server ./mcp-server
RUN cd mcp-server && npm install && npm run build

# Copy entrypoint and supervisor configuration
COPY docker/entrypoint.sh /entrypoint.sh
COPY docker/supervisord.conf /etc/supervisor/conf.d/supervisord.conf

# Make entrypoint executable
RUN chmod +x /entrypoint.sh

# Set production environment variables
ENV NODE_ENV=production
ENV PORT=3000
ENV HOSTNAME=0.0.0.0

# Expose the application port
# Note: When using Tailscale Serve, port 443 is also available on your Tailnet
EXPOSE 3000

# Define persistent storage volumes
# - /app/data: SQLite database and uploaded images
# - /var/lib/tailscale: Tailscale authentication state
VOLUME ["/app/data", "/var/lib/tailscale"]

# Health check to verify the application is running
HEALTHCHECK --interval=30s --timeout=10s --start-period=40s --retries=3 \
    CMD wget -q --spider http://localhost:3000/api/stats || exit 1

# Start the container using the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]
